name: hashcash
version: 1.0.0
author: Kevin Segaud<segaud.kevin@gmail.com>
homepage: https://github.com/Kleak/HashCash
description: |-
  Dart implementation of HashCash.

  see http://www.hashcash.org/ for more information.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: ">=1.1.1 <2.0.0"
dev_dependencies:
  test: any
  benchmark_harness: any
